### PR TITLE
1858 bug rollup builds failing

### LINKED ISSUE #1858: [Bug?]: rollup builds failing
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Rollup builds for React related packages are silently failing due to using outdated settings.

### Expected behavior 🤔

Build should be successful

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Context 🔦

All next packages are shipping only types and no content.

### Your environment 🌎

_No response_

### PR DESCRIPTION
**Pull request by caseybaggz**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?
closes #1858 

## What is the new behavior?
- Updates React lib to use `tsup` to build and generate types which is more reliable and React 19 compatible.
- Updates workspace TS settings to latest OS standard (i.e. matches Tanstack since that suite is pretty huge and compatible for everything)
- Fixes TS errors (i.e. lint errors & build errors like circular dependencies, etc.)

### CODE REVIEW

File: packages/react/src/index.ts [hunk 1]
```diff
@@ -30,7 +30,7 @@ export * from './components/Table.tsx'
 export * from './components/Tag.tsx'
 export * from './components/Textarea.tsx'
 export * from './components/TextLink.tsx'
-export * from './components/Toast.tsx'
+export * from './components/toast.tsx'
```
Comment (kathydlavoie-ps) [inline packages/react/src/index.ts:33]: should this be uppercased?

File: tsconfig.react.json [hunk 2]
```diff
@@ -5,6 +5,6 @@
     "noEmit": true,
     "jsx": "react-jsxdev",
     "lib": ["DOM", "es2015"],
-    "moduleResolution": "bundler"
+    "moduleResolution": "Bundler"
```
Comment (kathydlavoie-ps) [inline tsconfig.react.json:8]: I don't know if it makes a difference but should this be "bundler"?
