### PR TITLE
Fix/1199 date format cursor

### LINKED ISSUE #1199: [Bug?]: useAutoDateFormat - editing from the middle loses cursor position
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When editing within the date string (characters on either side of the cursor), as soon as a character is deleted the cursor jumps to the end.

https://user-images.githubusercontent.com/1745718/228276497-9c3acf46-bc4f-4196-b871-36c1cb2673f7.mov

### Expected behavior 🤔

Cursor position should be preserved.
It would also be nice if the delimiters did not adjust (e.g., 01/03/2000 -> 01/0/2000 when the 3 is deleted), but this would require some more advanced control and adjustment/validity checks.

### Steps to reproduce 🕹

Steps:
https://codesandbox.io/s/ps-react-typescript-forked-4t8nn5

1. Go to the sandbox included above or use the local dev sandbox (Input page)
2. Enter a full date
3. Move back using the arrow keys or mouse to the day or month
4. Backspace or delete the character
5. Enter a new number

### Context 🔦

_No response_

### Your environment 🌎

_No response_

### PR DESCRIPTION
**Pull request by Rykus0**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] infrastructure changes
- [ ] Other... Please describe:

## What is the current behavior?

closes #1199 

## What is the new behavior?
Cursor will be where expected after automatic updates
Users may type and delete delimiters ("/") and will format appropriately
Does not format when characters are removed
Formats on blur to account for cases where characters are replaced or deleted and formatting was not applied

Adds test cases for multiple input scenarios and duplicates those tests for the alternate dd/mm/yyyy format

## Other information
[Updated Sandbox](https://codesandbox.io/s/ps-react-typescript-forked-zypxq7)

### CODE REVIEW

File: packages/react-utils/src/hooks/useAutoFormatDate.ts [hunk 1]
```diff
@@ -52,269 +88,237 @@ function defaultAutoFormatOptions(options?: AutoFormatOptions) {
...
   prevValue: string
   value: string
 }
 
-function sanitizeDate(options: SanitizeOptions) {
-  const { value } = options
-  const template = getTemplate(options.pattern, options.blocks)
-  // Only allow numeric characters
-  const cleanVal = value.replace(/[^0-9]/gm, '')
+function formatDateInput(options: FormatOptions) {
```
Comment (caseybaggz) [inline packages/react-utils/src/hooks/useAutoFormatDate.ts:103]: This is a really large function that is handling more logic than just formating. I would love to see this broken out into multiple functions with single responsibilities to keep the code:

1. cleaner
2. easier to read
3. easier to debug
4. most importantly - reduce the risks of bugs (i.e. large functions are more fragile by nature)

Common practice via code smells are that if there is an area in a function where you are defining new `const/let` outside of the start of the block - that should be a new function.

**Review by caseybaggz — APPROVED** [review]

**Review by caseybaggz — APPROVED** [review]
